//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="WebService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WebService", ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService/HelloWorld", ReplyAction="*")]
        ConsoleAppClient.ServiceReference.HelloWorldResponse HelloWorld(ConsoleAppClient.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.HelloWorldResponse> HelloWorldAsync(ConsoleAppClient.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name conversion from namespace WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService/ConvertTemperature", ReplyAction="*")]
        ConsoleAppClient.ServiceReference.ConvertTemperatureResponse ConvertTemperature(ConsoleAppClient.ServiceReference.ConvertTemperatureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/ConvertTemperature", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.ConvertTemperatureResponse> ConvertTemperatureAsync(ConsoleAppClient.ServiceReference.ConvertTemperatureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/ConvertRonToEuro", ReplyAction="*")]
        double ConvertRonToEuro(double ronCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/ConvertRonToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConvertRonToEuroAsync(double ronCurrency);
        
        // CODEGEN: Generating message contract since element name GetListItemsResult from namespace WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetListItems", ReplyAction="*")]
        ConsoleAppClient.ServiceReference.GetListItemsResponse GetListItems(ConsoleAppClient.ServiceReference.GetListItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetListItems", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.GetListItemsResponse> GetListItemsAsync(ConsoleAppClient.ServiceReference.GetListItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetDateTime", ReplyAction="*")]
        System.DateTime GetDateTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="WebService/GetDateTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleAppClient.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleAppClient.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertTemperatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertTemperature", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.ConvertTemperatureRequestBody Body;
        
        public ConvertTemperatureRequest() {
        }
        
        public ConvertTemperatureRequest(ConsoleAppClient.ServiceReference.ConvertTemperatureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService")]
    public partial class ConvertTemperatureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double temperature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string conversion;
        
        public ConvertTemperatureRequestBody() {
        }
        
        public ConvertTemperatureRequestBody(double temperature, string conversion) {
            this.temperature = temperature;
            this.conversion = conversion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertTemperatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertTemperatureResponse", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.ConvertTemperatureResponseBody Body;
        
        public ConvertTemperatureResponse() {
        }
        
        public ConvertTemperatureResponse(ConsoleAppClient.ServiceReference.ConvertTemperatureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService")]
    public partial class ConvertTemperatureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConvertTemperatureResult;
        
        public ConvertTemperatureResponseBody() {
        }
        
        public ConvertTemperatureResponseBody(double ConvertTemperatureResult) {
            this.ConvertTemperatureResult = ConvertTemperatureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItems", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.GetListItemsRequestBody Body;
        
        public GetListItemsRequest() {
        }
        
        public GetListItemsRequest(ConsoleAppClient.ServiceReference.GetListItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListItemsRequestBody {
        
        public GetListItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListItemsResponse", Namespace="WebService", Order=0)]
        public ConsoleAppClient.ServiceReference.GetListItemsResponseBody Body;
        
        public GetListItemsResponse() {
        }
        
        public GetListItemsResponse(ConsoleAppClient.ServiceReference.GetListItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WebService")]
    public partial class GetListItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppClient.ServiceReference.ArrayOfString GetListItemsResult;
        
        public GetListItemsResponseBody() {
        }
        
        public GetListItemsResponseBody(ConsoleAppClient.ServiceReference.ArrayOfString GetListItemsResult) {
            this.GetListItemsResult = GetListItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ConsoleAppClient.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleAppClient.ServiceReference.WebServiceSoap>, ConsoleAppClient.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppClient.ServiceReference.HelloWorldResponse ConsoleAppClient.ServiceReference.WebServiceSoap.HelloWorld(ConsoleAppClient.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleAppClient.ServiceReference.HelloWorldRequest inValue = new ConsoleAppClient.ServiceReference.HelloWorldRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.HelloWorldRequestBody();
            ConsoleAppClient.ServiceReference.HelloWorldResponse retVal = ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.HelloWorldResponse> ConsoleAppClient.ServiceReference.WebServiceSoap.HelloWorldAsync(ConsoleAppClient.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ConsoleAppClient.ServiceReference.HelloWorldRequest inValue = new ConsoleAppClient.ServiceReference.HelloWorldRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.HelloWorldRequestBody();
            return ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppClient.ServiceReference.ConvertTemperatureResponse ConsoleAppClient.ServiceReference.WebServiceSoap.ConvertTemperature(ConsoleAppClient.ServiceReference.ConvertTemperatureRequest request) {
            return base.Channel.ConvertTemperature(request);
        }
        
        public double ConvertTemperature(double temperature, string conversion) {
            ConsoleAppClient.ServiceReference.ConvertTemperatureRequest inValue = new ConsoleAppClient.ServiceReference.ConvertTemperatureRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.ConvertTemperatureRequestBody();
            inValue.Body.temperature = temperature;
            inValue.Body.conversion = conversion;
            ConsoleAppClient.ServiceReference.ConvertTemperatureResponse retVal = ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).ConvertTemperature(inValue);
            return retVal.Body.ConvertTemperatureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.ConvertTemperatureResponse> ConsoleAppClient.ServiceReference.WebServiceSoap.ConvertTemperatureAsync(ConsoleAppClient.ServiceReference.ConvertTemperatureRequest request) {
            return base.Channel.ConvertTemperatureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.ConvertTemperatureResponse> ConvertTemperatureAsync(double temperature, string conversion) {
            ConsoleAppClient.ServiceReference.ConvertTemperatureRequest inValue = new ConsoleAppClient.ServiceReference.ConvertTemperatureRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.ConvertTemperatureRequestBody();
            inValue.Body.temperature = temperature;
            inValue.Body.conversion = conversion;
            return ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).ConvertTemperatureAsync(inValue);
        }
        
        public double ConvertRonToEuro(double ronCurrency) {
            return base.Channel.ConvertRonToEuro(ronCurrency);
        }
        
        public System.Threading.Tasks.Task<double> ConvertRonToEuroAsync(double ronCurrency) {
            return base.Channel.ConvertRonToEuroAsync(ronCurrency);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppClient.ServiceReference.GetListItemsResponse ConsoleAppClient.ServiceReference.WebServiceSoap.GetListItems(ConsoleAppClient.ServiceReference.GetListItemsRequest request) {
            return base.Channel.GetListItems(request);
        }
        
        public ConsoleAppClient.ServiceReference.ArrayOfString GetListItems() {
            ConsoleAppClient.ServiceReference.GetListItemsRequest inValue = new ConsoleAppClient.ServiceReference.GetListItemsRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.GetListItemsRequestBody();
            ConsoleAppClient.ServiceReference.GetListItemsResponse retVal = ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).GetListItems(inValue);
            return retVal.Body.GetListItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.GetListItemsResponse> ConsoleAppClient.ServiceReference.WebServiceSoap.GetListItemsAsync(ConsoleAppClient.ServiceReference.GetListItemsRequest request) {
            return base.Channel.GetListItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppClient.ServiceReference.GetListItemsResponse> GetListItemsAsync() {
            ConsoleAppClient.ServiceReference.GetListItemsRequest inValue = new ConsoleAppClient.ServiceReference.GetListItemsRequest();
            inValue.Body = new ConsoleAppClient.ServiceReference.GetListItemsRequestBody();
            return ((ConsoleAppClient.ServiceReference.WebServiceSoap)(this)).GetListItemsAsync(inValue);
        }
        
        public System.DateTime GetDateTime() {
            return base.Channel.GetDateTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateTimeAsync() {
            return base.Channel.GetDateTimeAsync();
        }
    }
}
